function error() {
    try {
        aleeeeeert("nofunciona");
    } catch(error) {
        throw new EvalError(["Se ha producido un error",'ejercicio13.js','100']);
    }
};

